apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/crossplane-operator/
  - ../../components/crossplane-providers/
  - ../../components/crossplane-provider-config/
