projects:

  cluster-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
      - ${INFRA_GITOPS_REPO}
      - https://charts.openshift.io
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'

applications:

  redhat-developer-hub:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    source:
      path: applications/redhat-developer-hub
    destination:
      namespace: redhat-developer-hub
    extraFields: |
      ignoreDifferences:
        - group: 'apps'
          jsonPointers:
            - /spec/volumeClaimTemplates
          kind: StatefulSet
        - group: 'route.openshift.io'
          jsonPointers:
            - /spec/host
          kind: Route    
