apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redhat-developer-hub

resources:
  - ./namespace.yaml
  - ./cluster-role-binding.yaml

# helmGlobals:
#   chartHome: ../../helm/charts

# helmCharts:
#   - name: redhat-developer-hub
#     releaseName: redhat-developer-hub
#     namespace: redhat-developer-hub
#     valuesFile: values.yaml
