apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./keycloak-client-secret-backstage.yaml
  - ./cluster-role-binding.yaml
  - ./console-link.yaml
  - ./client-secret-patch.yaml
