apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  redhat-developer-hub

resources:
  - ./namespace.yaml

helmCharts:
  - name: redhat-developer-hub
    repo: https://charts.openshift.io
    releaseName: redhat-developer-hub
    namespace: redhat-developer-hub
    valuesFile: values.yaml
