apiVersion: v1
kind: Secret
metadata:
  name: openshift-helm-charts
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: openshift-helm-charts
  url: https://charts.openshift.io
  type: helm
