apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources: 
- ./namespace.yaml
- ./role-binding.yaml

helmCharts:
  - name: crossplane
    releaseName: crossplane
    repo: https://charts.crossplane.io/stable
    namespace: crossplane-system
