apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: backstage
  namespace: rhsso
  labels:
    app: rhsso
spec:
  realmSelector:
    matchLabels:
      app: rhsso
  client:
    id: backstage
    clientId: backstage
    secret: ocp-secret
    rootUrl: https://developer-hub-redhat-developer-hub.apps.${CLUSTER_BASE_DOMAIN}
    redirectUris:
      - /oauth2/callback
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
      - roles
    consentRequired: false
    serviceAccountsEnabled: true
  serviceAccountRealmRoles:
    - default-roles-myorg
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users
